---
- hosts: Front
  tasks:
    - name: install appache2
      apt: name=apache2 state=present

    - name: install vim
      apt: name=vim state=present

    - name: install php7.0
      apt: name=apache2 state=present

    - name: install postfix
      apt: name=apache2 state=present
    
    - name: install proftpd
      apt: name=apache2 state=present


- hosts: Front
  tasks:
    - name: install appache2
      apt: name=apache2 state=present

    - name: install vim
      apt: name=vim state=present

    - name: install php7.0
      apt: name=apache2 state=present

    - name: install postfix
      apt: name=apache2 state=present
    
    - name: install proftpd
      apt: name=apache2 state=present
      